services:
  identity.api:
    image: identity.api
    ports:
      - "5000:8080"
    build:
      context: .
      dockerfile: Identity.API/Dockerfile

  ocelotgateway.api:
    image: ocelotgateway.api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: OcelotGateway.API/Dockerfile
  
  
  weather.api:
    image: weather.api
    build:
      context: .
      dockerfile: Weather.API/Dockerfile

  share:
    image: share
    build:
      context: .
      dockerfile: Share/Dockerfile

  backgroundservice:
    image: backgroundservice
    build:
      context: .
      dockerfile: BackgroundService/Dockerfile
    
  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672
    image: masstransit/rabbitmq