services:
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
    image: masstransit/rabbitmq
    
  backgroundservice:
    image: backgroundservice
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: BackgroundService/Dockerfile
      
  identity.api:
    image: identity.api
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    depends_on:
      - rabbitmq

  catalog.api:
    image: catalog.api
    ports:
      - "8082:8082"
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  ocelotgateway.api:
    image: ocelotgateway.api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: OcelotGateway.API/Dockerfile
    depends_on: 
      - identity.api
      - catalog.api
